resource "aws_iam_role" "ravion_access_read" {
  name = "${local.ravion_access_name}-read"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow", Action = ["sts:AssumeRole", "sts:SetSourceIdentity"]
      Principal = { AWS = length(var.ravion_access_read_trusted_principal_arns) > 0 ? var.ravion_access_read_trusted_principal_arns : ["arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}:root"] }
    }]
  })
  tags = local.ravion_access_tags
}

resource "aws_eks_access_entry" "ravion_access_read" {
  cluster_name      = module.cluster.cluster_name
  principal_arn     = aws_iam_role.ravion_access_read.arn
  type              = "STANDARD"
  kubernetes_groups = ["ravion:readers"]
  tags              = local.ravion_access_tags
}

resource "aws_eks_access_policy_association" "ravion_access_read" {
  cluster_name  = module.cluster.cluster_name
  principal_arn = aws_eks_access_entry.ravion_access_read.principal_arn
  policy_arn    = "arn:${data.aws_partition.current.partition}:eks::aws:cluster-access-policy/AmazonEKSViewPolicy"
  access_scope {
    type = "cluster"
  }
}

data "aws_iam_policy_document" "ravion_access" {
  statement {
    sid       = "DescribeThisCluster"
    actions   = ["eks:DescribeCluster"]
    resources = [module.cluster.cluster_arn]
  }
  statement {
    sid       = "DiscoverRelay"
    actions   = ["ec2:DescribeInstances", "ssm:DescribeInstanceInformation"]
    resources = ["*"] # These discovery APIs do not support resource-level IAM.
  }
  statement {
    sid       = "StartRelaySession"
    actions   = ["ssm:StartSession"]
    resources = [aws_instance.ravion_access_relay.arn]
    condition {
      test     = "Bool"
      variable = "ssm:SessionDocumentAccessCheck"
      values   = ["true"]
    }
  }
  statement {
    sid       = "OnlyPinnedEKSDocument"
    actions   = ["ssm:StartSession", "ssm:GetDocument"]
    resources = [aws_ssm_document.ravion_access.arn]
  }
  statement {
    sid     = "OpenSessionDataChannel"
    actions = ["ssmmessages:OpenDataChannel"]
    # Session IDs are generated by SSM. Opening a channel also requires the
    # bearer token returned by the scoped StartSession/ResumeSession calls.
    # SSM resource-tag conditions are not documented for ssmmessages actions.
    resources = ["arn:${data.aws_partition.current.partition}:ssm:${module.cluster.region}:${data.aws_caller_identity.current.account_id}:session/*"]
  }
  statement {
    sid       = "OwnSessions"
    actions   = ["ssm:ResumeSession", "ssm:TerminateSession"]
    resources = ["arn:${data.aws_partition.current.partition}:ssm:${module.cluster.region}:${data.aws_caller_identity.current.account_id}:session/*"]
    # Assumed-role session ARNs use the session name, not aws:userid. SSM's
    # system tag contains role-id:session-name and supports exact ownership.
    condition {
      test     = "StringEquals"
      variable = "ssm:resourceTag/aws:ssmmessages:session-id"
      values   = ["$${aws:userid}"]
    }
    condition {
      test     = "StringEquals"
      variable = "ssm:resourceTag/aws:ssmmessages:target-id"
      values   = [aws_instance.ravion_access_relay.id]
    }
  }
}

resource "aws_iam_role_policy" "ravion_access_read" {
  name   = "eks-ssm-access"
  role   = aws_iam_role.ravion_access_read.id
  policy = data.aws_iam_policy_document.ravion_access.json
}

resource "aws_iam_role_policy" "ravion_access_admin" {
  count  = var.ravion_runner_role_creation_enabled ? 1 : 0
  name   = "eks-ssm-access"
  role   = module.ravion_runner_role[0].role_name
  policy = data.aws_iam_policy_document.ravion_access.json
}
