apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.nodePool.name }}
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: kubernetes.io/arch
          operator: In
          values: {{ .Values.nodePool.architectures | toJson }}
        - key: karpenter.sh/capacity-type
          operator: In
          values: {{ .Values.nodePool.capacityTypes | toJson }}
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: {{ .Values.nodePool.instanceCategories | toJson }}
        # Skip older instance generations with worse price/performance.
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.ec2NodeClass.name }}
      expireAfter: {{ .Values.nodePool.expireAfter }}
  limits:
    cpu: {{ .Values.nodePool.cpuLimit }}
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
