{{- range $component := list "query" "store" "compactor" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-{{ $component }}
  namespace: {{ $.Release.Namespace }}
automountServiceAccountToken: false
{{- end }}
