description: Only available during the build, not at runtime. Use environment variables or secrets for runtime values.
id: build_environment_variables
label: Build environment variables
placeholder: |-
  {
    "NODE_ENV": "production",
    "API_URL": {
      "fromParameterStore": "my-secret"
    },
    "NPM_TOKEN": {
      "fromSecretManager": "arn:..."
    }
  }
required: false
type: object
