locals {
  region = coalesce(var.region, data.aws_region.current.region)
}

locals {
  default_tags = {
    ManagedBy = "terraform"
    Module    = "compute/lambda"
  }

  tags = merge(local.default_tags, var.tags)

  log_group_name = coalesce(var.log_group_name, "/aws/lambda/${var.name}")

  role_name = coalesce(var.role_name, "${var.name}-lambda-role")

  managed_policy_arns = distinct(concat(
    var.basic_execution_policy_enabled ? ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"] : [],
    var.vpc_execution_policy_enabled && var.vpc_config != null ? ["arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"] : [],
    var.role_managed_policy_arns
  ))

  lambda_role_arn = var.role_creation_enabled ? aws_iam_role.this[0].arn : var.role_arn

  create_code_bucket = (
    var.package_type == "Zip" &&
    var.filename == null &&
    var.s3_bucket == null &&
    var.s3_key == null
  )

  code_bucket_name = coalesce(
    var.code_bucket_name,
    "${var.name}-code-${data.aws_caller_identity.current.account_id}"
  )

  effective_s3_bucket = (
    var.s3_bucket != null ? var.s3_bucket :
    local.create_code_bucket ? module.code_bucket[0].bucket_id :
    null
  )

  effective_s3_key = (
    var.s3_key != null ? var.s3_key :
    local.create_code_bucket ? aws_s3_object.bootstrap_package[0].key :
    null
  )

  create_bootstrap_image = (
    var.package_type == "Image" &&
    var.image_uri == null &&
    var.ecr_repository_creation_enabled
  )

  bootstrap_image_tag = "ravion-bootstrap"

  bootstrap_image_uri = (
    local.create_bootstrap_image ?
    "${module.ecr[0].repository_url}:${local.bootstrap_image_tag}" :
    null
  )

  bootstrap_image_platform = var.architecture == "arm64" ? "linux/arm64" : "linux/amd64"

  effective_image_uri = (
    var.image_uri != null ? var.image_uri :
    local.bootstrap_image_uri
  )

  # Minimal valid zip containing `bootstrap` and `index.js` stubs so the
  # function can be created before the real artifact is uploaded. Embedded
  # as base64 (not generated by archive_file) so that saved planfiles can be
  # applied on a different machine without losing the artifact.
  bootstrap_package_zip_base64 = "UEsDBBQAAAAAAOmTrlzmIEd4EgAAABIAAAAJAAAAYm9vdHN0cmFwI1whL2Jpbi9zaApleGl0IDAKUEsDBBQAAAAAAOmTrlytngM7SgAAAEoAAAAIAAAAaW5kZXguanNleHBvcnRzLmhhbmRsZXIgPSBhc3luYyAoKSA9PiAoeyBzdGF0dXNDb2RlOiAyMDAsIGJvZHk6ICJwbGFjZWhvbGRlciIgfSk7ClBLAQIUAxQAAAAAAOmTrlzmIEd4EgAAABIAAAAJAAAAAAAAAAAAAACAAQAAAABib290c3RyYXBQSwECFAMUAAAAAADpk65crZ4DO0oAAABKAAAACAAAAAAAAAAAAAAAgAE5AAAAaW5kZXguanNQSwUGAAAAAAIAAgBtAAAAqQAAAAAA"

  # URL and event-source traffic always follows Ravion's deployment alias.
  aliases = merge(
    var.function_url_enabled || length(var.event_source_mappings) > 0 || anytrue([
      for permission in var.permissions : try(permission.function_url_auth_type, null) != null || try(permission.action, null) == "lambda:InvokeFunctionUrl"
    ]) ? { live = {} } : {},
    var.aliases
  )

  permissions_map = {
    for idx, permission in var.permissions : tostring(idx) => permission
  }

  event_source_mappings_map = {
    for idx, mapping in var.event_source_mappings : tostring(idx) => mapping
  }
}
